import {MapElements} from "../../enums/map-elements";

export const defaultMap = [
    [MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty],
    [MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty],
    [MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty],
    [MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty],
    [MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty],
    [MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty],
    [MapElements.Brick, MapElements.Brick, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Block, MapElements.Block, MapElements.Block, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Brick, MapElements.Brick],
    [MapElements.Block, MapElements.Block, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Block, MapElements.Block, MapElements.Block, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Block, MapElements.Block],
    [MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Water, MapElements.Water, MapElements.Water, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty],
    [MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Water, MapElements.Water, MapElements.Water, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty],
    [MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty],
    [MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty],
    [MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty],
    [MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Brick, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty],
    [MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Brick, MapElements.Empty, MapElements.Brick, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty, MapElements.Empty]
];
