import {MapElementTypes} from "../../enums/map-element-types";
import {Direction} from "../../enums/direction";
import {MapConfig} from "../../models/map-config";

export const defaultMap: MapConfig = {
    defaultUserPosition: {
        x: 5,
        y: 14,
        direction: Direction.Up,
    },
    bitmap: [
        [MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty],
        [MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty],
        [MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty],
        [MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty],
        [MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty],
        [MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty],
        [MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Sand, MapElementTypes.Sand, MapElementTypes.Sand, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Brick],
        [MapElementTypes.Sand, MapElementTypes.Sand, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Sand, MapElementTypes.Sand, MapElementTypes.Sand, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Sand, MapElementTypes.Sand],
        [MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Water, MapElementTypes.Water, MapElementTypes.Water, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty],
        [MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Water, MapElementTypes.Water, MapElementTypes.Water, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty],
        [MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty],
        [MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty],
        [MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty],
        [MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty],
        [MapElementTypes.Tree, MapElementTypes.Tree, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Brick, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Empty, MapElementTypes.Tree, MapElementTypes.Tree]
    ]
};
